Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blogapp/", include("blogapp.urls")),
]

blogapp/urls.py
from django.urls import path
from . import views

app_name = "blogapp"

urlpatterns =[
    path("", views.IndexView.as_view(), name="index"),
    path("post/<int:pk>/", views.PostDetailView.as_view(), name="post_detail"),
    path("newpost/", views.CreatePostView.as_view(), name="create_post"),
    path("update/<int:pk>", views.UpdatePost.as_view(), name="update"),
    path("delete/<int:pk>", views.DeletePost.as_view(), name="delete"),
    path("comment/<int:pk>", views.CommentForm.as_view(), name="comment")

]

blogapp/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse_lazy

# Create your models here.

class Blog(models.Model):
    blog_name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.blog_name

        
    
class Author(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name
    
    

class Post(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    update_date = models.DateField("Last update", default=timezone.now)
    tags = models.ManyToManyField("Tag", blank=True, related_name="tags_on_post")
    author = models.ForeignKey(Author,on_delete=models.CASCADE)
    
    def __str__(self):
        return self.title  
    
    def get_absolute_url(self):
        return reverse_lazy("blogapp:post_detail", args=[self.id])



class Tag(models.Model):
     tag_name = models.CharField(max_length=100)
     posts = models.ManyToManyField(Post, blank=True, related_name="posts_under_tag")
     
     def __str__(self):
        return self.tag_name
    

         
    
class Comment(models.Model):
    post = models.ForeignKey(Post,  on_delete=models.CASCADE)
    comments = models.TextField()
    comment_PostedDate = models.DateTimeField("Date of comments", default=timezone.now)
    name = models.CharField(max_length=100)
    
    def __str__(self):
         return f"{self.name}: {self.comments}"
    
    def get_absolute_url(self):
        return reverse_lazy("blogapp:comment", args=[self.id])

blogapp/forms.py
from django import forms
from .models import Post, Tag, Comment

class PostForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ["title", "author", "body", "tags", ]
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["tags"].widget = forms.SelectMultiple(attrs={"list":"tag_list"})
        self.fields["tags"].queryset = Tag.objects.all()
        

blogapp/views.py
from typing import Any
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic 
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from blogapp.models import Blog, Post, Comment, Tag, Author
from django.urls import reverse_lazy
from .forms import PostForm



# Create your views here.

class IndexView(generic.ListView):
    template_name = "blogapp/index.html"
    context_object_name = "post_list"
    
    def get_queryset(self):
        return Post.objects.all().order_by("-update_date")
    
    

class PostDetailView(generic.DetailView):
    model = Post
    template_name = "blogapp/detail.html"
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        post = self.get_object()
        comments = Comment.objects.filter(post=post)
        context["comment_list"] = comments
        return context
    

class CreatePostView(generic.CreateView):
    model = Post
    form_class = PostForm
    template_name = "blogapp/create_post.html"



class CommentForm(CreateView):
    model = Comment
    fields = ["comments", "name"]
    context_object_name = "comment_list"
    
    def form_valid(self, form):
        post_id = self.kwargs['pk'] 
        post = get_object_or_404(Post, id=post_id)
        form.instance.post = post
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('blogapp:post_detail', args=[self.kwargs['pk']])
    
    
    
class UpdatePost(UpdateView):
    model = Post
    fields = ["title", "body", "author", "tags"]
    template_name = "blogapp/create_post.html"
    
    
class DeletePost(DeleteView):
    model = Post
    success_url = reverse_lazy("blogapp:index")

blogapp/templates/blogapp/base.html
<!doctype HTML>
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'blogapp:index' %}">ハイデッカー家の猫日記</a>
        </nav>
        <div class="container mt-4">
        {% block main %}
        <p>※コンテンツがありません。</p>
        {% endblock %}
        </div>
    </body>
</html>

blogapp/templates/blogapp/comment_form.html
{% extends "blogapp/base.html" %}
{% block main %}

<h2> コメントを投稿しよう!</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Comment it">
</form>
{% endblock %}

blogapp/templates/blogapp/create_post.html
{% extends "blogapp/base.html" %}
{% block main %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <label for="tag">Tags</label>
    <input list="tag_list" id="tag" name="tag">
    <datalist id="tag_list">
        {% for tag in tags %}
        <option value="{{ tag.id }}">{{ tag.name }}</option>
        {%endfor%}
    </datalist>
    <br>
    <input type="submit" value="Post">

</form>
{% endblock %}

blogapp/templates/blogapp/detail.html
{% extends "blogapp/base.html" %}
{% block main %}

    <h7>投稿者: {{ post.author }} <br> 更新日: {{ post.update_date }}</h7>

    <br>
    <br>

    <h1>{{ post.title }}</h1>
    
    {% if post.tags.all %}
        <h3>
            {% for tag in post.tags.all %}
                #{{ tag.tag_name }}
            {% endfor %}
        </h3>
    {% endif %}

    <br>

    <p>{{ post.body }}</p>

    <br>
    <br>

    <h4>コメント:</h4>
    <ul>
        {% for comment in comment_list %}
            <li>
                <i><h6>{{comment.comments}}</h6></i>
                <h9>投稿者: {{ comment.name }}</h9>
                <h9>投稿日: {{ comment.comment_PostedDate }}</h9>
            </li>
            {% endfor %}
        </ul>
    
    <br>
    <br>

    <a href="{% url 'blogapp:comment' object.pk %}">コメントを投稿する</a>
    <br>
    <a href="{% url 'blogapp:update' object.pk %}">編集</a>
    <br>
    <a href="{% url 'blogapp:delete' object.pk %}">削除</a>
{% endblock %}

blogapp/templates/blogapp/index.html
{% extends "blogapp/base.html" %}
{% block main %}
    <head>
        <title>ハイデッカー家の猫日記</title>

        <h2>最近の投稿:</h2>
        <ul>
        {% for post in post_list %}
            <li>
                <strong><a href="{% url 'blogapp:post_detail' post.id %}">{{ post.title }}</a></strong>
                <br>
                {{ post.author }}
                {{ post.update_date }}
            </li>
            {% endfor %}
        </ul>

        <p><a href="{% url 'blogapp:create_post' %}">新規作成</a></p>
{% endblock %}

blogapp/templates/blogapp/post_confirm_delete.html
{% extends "blogapp/base.html" %}
{% block main %}

<h1> 投稿の削除 </h1>
<p>本当に <strong>{{ object.title }}</strong>を削除しますか？</p>
<form method="post">
    {% csrf_token %}
    <input type="submit" value="Delete">
    <input type="reset" value="Cancel">
</form>
{% endblock %}